// Search
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const CLEAR_SEARCH_INPUT = 'CLEAR_SEARCH_INPUT';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
// Logout
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
// Auth token verification
export const AUTH_VERIFICATION = 'AUTH_VERIFICATION';
// Users
export const GET_USERS = 'GET_USERS';
// Modal
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
// Form
export const SET_FORM_FIELDS = 'SET_FORM_FIELDS';
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const SET_USER_AUTOCOMPLETE = 'SET_USER_AUTOCOMPLETE';
export const FORM_SUCCESS = 'FORM_SUCCESS';
export const SET_SONG_FORM = 'SET_SONG_FORM';
export const UPDATE_SONG_FORM = 'UPDATE_SONG_FORM';
export const UPDATE_USER_SETTINGS_FIELD = 'UPDATE_USER_SETTINGS_FIELD';
export const CLEAR_INPUT_FIELDS = 'CLEAR_INPUT_FIELDS';

// Model
export const SET_MODEL = 'SET_MODEL';
export const UPDATE_MODEL = 'UPDATE_MODEL';
export const DELETE_MODEL = 'DELETE_MODEL';

// middleware
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

// Main page
export const SHOW_SELECT = 'SHOW_SELECT';
export const USER_SHOW_SELECT = 'USER_SHOW_SELECT';

// Playlist
export const GET_SHOW_PLAYLISTS = 'GET_SHOW_PLAYLISTS';
export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const ADD_PLAYLIST_TO_SIDEBAR = 'ADD_PLAYLIST_TO_SIDEBAR';
export const CURRENT_PLAYLIST = 'CURRENT_PLAYLIST';
export const ADD_TRACK = 'ADD_TRACK';
export const DELETE_TRACK = 'DELETE_TRACK';
export const REORDER_SONGS = 'REORDER_SONGS';
export const UPDATE_PLAYLIST_SONGS = 'UPDATE_PLAYLIST_SONGS';
export const RESET_CURRENT_PLAYLIST = 'RESET_CURRENT_PLAYLIST';

// Now Playing
export const SET_NOW_PLAYING = 'SET_NOW_PLAYING';

// Show
export const GET_SHOW = 'GET_SHOW';

// error
export const SUBMIT_ERROR = 'SUBMIT_ERROR';
export const SNACKBAR_MESSAGE = 'SNACKBAR_MESSAGE';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// UI
export const TOGGLE_PLAYLIST_DRAWER = 'TOGGLE_PLAYLIST_DRAWER';
