// Search
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const CLEAR_SEARCH_INPUT = 'CLEAR_SEARCH_INPUT';
// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const AUTH_VERIFICATION = 'AUTH_VERIFICATION';

export const GET_USERS = 'GET_USERS';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';
